In [4]:
#Create two numpy arrays.

import numpy as np

print('1D Array of Strings')
arr1=np.array([1.5,2.5,3.5,4.5,5.5,6.5])

print(arr1)

print('2D Array of Strings')
arr2=np.array([['ab','bc','cd','de','ef'],['fg','gh','hi','ij','jk']])

print(arr2)


1D Array of Strings
[1.5 2.5 3.5 4.5 5.5 6.5]
2D Array of Strings
[['ab' 'bc' 'cd' 'de' 'ef']
 ['fg' 'gh' 'hi' 'ij' 'jk']]


In [9]:
#For the arrays arr1 and arr2 created in Q.No.1, display the following properties:

import numpy as np

print(arr1.dtype)
print(arr2.dtype)


print(arr1.shape)
print(arr2.shape)

a1=arr1.reshape(2,3)
print(a1)

a2=arr2.reshape(-1)
print(a2)




float64
<U2
(6,)
(2, 5)
[[1.5 2.5 3.5]
 [4.5 5.5 6.5]]
['ab' 'bc' 'cd' 'de' 'ef' 'fg' 'gh' 'hi' 'ij' 'jk']


In [14]:
#Create a two dimensional array called arr3, of 3 rows and 4 columns which is initialized to zeroes.

import numpy as np

print('2D array with 0:')
arr3=np.zeros([3,4],dtype=int)
print(arr3)

print('1D array with 1:')
arr4=np.ones(6,dtype=int)
print(arr4)








2D array with 0:
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
1D array with 1:
[1 1 1 1 1 1]


In [21]:
#list1 with the elements 10,20,30,40,50.

import numpy as np

list1=[10,20,30,40,50]

arr5=np.asarray(list1,dtype=float)


print(list1)
print('Array 5:')
print(arr5)

print('Array 6:')
arr6=np.fromiter(list1,dtype=float)
print(arr6)






[10, 20, 30, 40, 50]
Array 5:
[10. 20. 30. 40. 50.]
Array 6:
[10. 20. 30. 40. 50.]


In [25]:
#Create a numpy array called arr7 using the method arange.

import numpy as np

arr7=np.arange(12,99,3,int)
print(arr7)

arr8=np.linspace(12,99,50)
print(arr8)

[12 15 18 21 24 27 30 33 36 39 42 45 48 51 54 57 60 63 66 69 72 75 78 81
 84 87 90 93 96]
[12.         13.7755102  15.55102041 17.32653061 19.10204082 20.87755102
 22.65306122 24.42857143 26.20408163 27.97959184 29.75510204 31.53061224
 33.30612245 35.08163265 36.85714286 38.63265306 40.40816327 42.18367347
 43.95918367 45.73469388 47.51020408 49.28571429 51.06122449 52.83673469
 54.6122449  56.3877551  58.16326531 59.93877551 61.71428571 63.48979592
 65.26530612 67.04081633 68.81632653 70.59183673 72.36734694 74.14285714
 75.91836735 77.69387755 79.46938776 81.24489796 83.02040816 84.79591837
 86.57142857 88.34693878 90.12244898 91.89795918 93.67346939 95.44897959
 97.2244898  99.        ]


In [27]:
#In the array arr2 defined in Q.No. 1,

print('2D Array of Strings')
arr2=np.array([['ab','bc','cd','de','ef'],['fg','gh','hi','ij','jk']])

print(arr2)

print(arr2[0:1])

print(arr2[1][3])

print (arr2[1])



2D Array of Strings
[['ab' 'bc' 'cd' 'de' 'ef']
 ['fg' 'gh' 'hi' 'ij' 'jk']]
[['ab' 'bc' 'cd' 'de' 'ef']]
ij
['fg' 'gh' 'hi' 'ij' 'jk']


In [35]:
#Create a two dimensional array called arr9 

import numpy as np

arr9=np.array([[101, 322, 768], [233, 124, 390], [534, 122, 216]])
print(arr9)

print('Displaying the required array using advanced indexing:')
arr10=arr9[[0,0,1,2],[0,1,2,1]]
print(arr10)

print('using Indexing:')
arr11=arr9[0:2,1:3]
print(arr11)


[[101 322 768]
 [233 124 390]
 [534 122 216]]
Displaying the required array using advanced indexing:
[101 322 390 122]
using Indexing:
[[322 768]
 [124 390]]


In [41]:
#From array arr9 created in Q.No. 7,

import numpy as np

arr9=np.array([[101, 322, 768], [233, 124, 390], [534, 122, 216]])
print(arr9)

print('Boolean Indexing :')
print(arr9[arr9>200])

print('Not a number:')
print(arr9[~np.isnan(arr9)])
print()
print(arr9[~np.isnan(arr9)])
print('Non float Elements:')
print(arr9[arr9.dtype!='float'])


print('Broadcasting:')
arr11=np.array([10,20,30])

print('First+Second:')
print(arr9+arr11)


[[101 322 768]
 [233 124 390]
 [534 122 216]]
Boolean Indexing :
[322 768 233 390 534 216]
Not a number:
[101 322 768 233 124 390 534 122 216]

[101 322 768 233 124 390 534 122 216]
Non float Elements:
[[[101 322 768]
  [233 124 390]
  [534 122 216]]]
Broadcasting:
First+Second:
[[111 342 798]
 [243 144 420]
 [544 142 246]]


In [48]:
#For the array arr9, find its transpose

import numpy as np

arr9=np.array([[101, 322, 768], [233, 124, 390], [534, 122, 216]])
print(arr9)

print('After Transpose')
print(arr9.T)

print('joining of the array1 and array4 along axis 0:')

arr1=np.array([1.5,2.5,3.5,4.5,5.5,6.5])

#print(arr1)

arr4=np.ones(6,dtype=int)
#print(arr4)

print(np.concatenate((arr1,arr4),axis=0))

[[101 322 768]
 [233 124 390]
 [534 122 216]]
After Transpose
[[101 233 534]
 [322 124 122]
 [768 390 216]]
joining of the array1 and array4 along axis 0:
[1.5 2.5 3.5 4.5 5.5 6.5 1.  1.  1.  1.  1.  1. ]


In [56]:
#Using any two 2-dimensional arrays,

import numpy as np

print('hstack:')
ar1 = np.array([[1, 2],
                [3, 4],
                [5, 6]])

ar2 = np.array([[0, 0],
                [1, 1],
                [2, 2]])

ar_h = np.hstack((ar1, ar2))

print(ar_h)

print('vstack:')
ar1 = np.array([[1, 2],
                [3, 4],
                [5, 6]])

ar2 = np.array([[0, 0],
                [1, 1],
                [2, 2]])

ar_v = np.vstack((ar1, ar2))

print(ar_v)


print('hsplit and vsplit:')
x = np.arange(20).reshape(5, 4)
print(x)
print('hsplit:')
print(np.hsplit(x,2))
print('vsplit:')
print(np.vsplit(x,1))

hstack:
[[1 2 0 0]
 [3 4 1 1]
 [5 6 2 2]]
vstack:
[[1 2]
 [3 4]
 [5 6]
 [0 0]
 [1 1]
 [2 2]]
hsplit and vsplit:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]
hsplit:
[array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13],
       [16, 17]]), array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15],
       [18, 19]])]
vsplit:
[array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])]
